version: "3.9"

services:

  frontend:
    build: ./my-react-app
    volumes:
    - ./my-react-app:/app
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    volumes:
    - ./backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    # environment:
    #   - DB_HOST=db
    #   - DB_USER=root
    #   - DB_PASSWORD=root
    #   - DB_NAME=testdb
    env_file:
    - ./.env

  db:
    image: mysql:8
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME} 
    ports:
      - "3306:3306"
    volumes:
    - mysql-data:/var/lib/mysql
    - mysql-backups:/backups
volumes:
  mysql-data:
  mysql-backups: