name: Frontend CI First ci pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
        node-version: "18"

      - name: 📦 Install Dependencies
        run: npm install
        working-directory: my-react-app

      - name: 🏗️ Build Project
        run: npm run build
        working-directory: my-react-app

      - name: 🧪 Run Tests
        # run: npm test
        run: echo "No tests yet"
        working-directory: my-react-app