name: CI + CD Pipeline

on:
  push:
    branches: ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🟢 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: 📦 Install Dependencies
        run: npm install
        working-directory: my-react-app

      - name: 🏗️ Build Project
        run: npm run build
        working-directory: my-react-app

      - name: 📤 Upload build (dist)
        uses: actions/upload-pages-artifact@v3
        with:
          path: my-react-app/dist

      - name: 🚀 Deploy to GitHub Pages
        uses: actions/deploy-pages@v4